--CREATE SCHEMAS

CREATE SCHEMA Produccion;
CREATE SCHEMA [Plan];
CREATE SCHEMA [User];
CREATE SCHEMA Registro; 
CREATE SCHEMA Rajo;
CREATE SCHEMA Factor;
CREATE SCHEMA Camion;
CREATE SCHEMA Fecha;
CREATE SCHEMA Sector;
CREATE SCHEMA Pala;
CREATE SCHEMA Material;
CREATE SCHEMA Vueltas;
CREATE SCHEMA Ciclo;
-----CREATE TABLES

/**

CREATE TABLE Fecha.Fecha(
	ID_FECHA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	FECHA DATE NOT NULL UNIQUE
);

CREATE TABLE Sector.Zona(
	ID_ZONA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE Sector.Origen(
	ID_ORIGEN SMALLINT IDENTITY(1,1) PRIMARY KEY,
	ID_ZONA SMALLINT REFERENCES Sector.ZONA(ID_ZONA),
	NOMBRE VARCHAR(24) NOT NULL UNIQUE
);


CREATE TABLE Pala.PALA(
	ID_PALA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE Material.MATERIAL(
	ID_MATERIAL SMALLINT IDENTITY(1,1) PRIMARY KEY, 
	ID_ZONA SMALLINT REFERENCES Sector.ZONA(ID_ZONA),
	NOMBRE VARCHAR(18) NOT NULL UNIQUE
);

CREATE TABLE Camion.FLOTA(
	ID_FLOTA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE Camion.CAMION(
	ID_CAMION SMALLINT IDENTITY(1,1) PRIMARY KEY,
	ID_FLOTA SMALLINT REFERENCES Camion.FLOTA(ID_FLOTA),
	NOMBRE VARCHAR(8) NOT NULL UNIQUE
);
*/

CREATE TABLE Factor.FACTOR(
	ID_FACTOR SMALLINT IDENTITY(1,1) PRIMARY KEY,
	TONELAJE REAL NOT NULL
);

CREATE TABLE Factor.FACTOR_CARGA(
	ID_FACTOR_CARGA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	ID_ZONA SMALLINT REFERENCES Sector.ZONA(ID_ZONA),
	ID_FLOTA SMALLINT REFERENCES Camion.FLOTA(ID_FLOTA),
	ID_FACTOR SMALLINT REFERENCES Factor.FACTOR(ID_FACTOR),
	ID_FECHA_INI SMALLINT REFERENCES Fecha.FECHA(ID_FECHA),
	ID_FECHA_FIN SMALLINT REFERENCES Fecha.FECHA(ID_FECHA)
);

CREATE TABLE Rajo.RAJO(
	ID_RAJO TINYINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE Sector.DESTINO(
	ID_DESTINO SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(24) NOT NULL UNIQUE
);

CREATE TABLE Vueltas.VUELTAS(
	ID_VUELTAS SMALLINT IDENTITY(1,1) PRIMARY KEY,
	CANTIDAD TINYINT NOT NULL
);

CREATE TABLE Ciclo.CICLO(
	ID_CICLO INT IDENTITY(1,1) PRIMARY KEY,
	ID_FECHA SMALLINT REFERENCES Fecha.FECHA(ID_FECHA),
	ID_PALA SMALLINT REFERENCES Pala.PALA(ID_PALA),
	ID_CAMION SMALLINT REFERENCES Camion.CAMION(ID_CAMION),
	ID_ZONA SMALLINT REFERENCES Sector.ZONA(ID_ZONA),
	ID_DESTINO SMALLINT REFERENCES Sector.DESTINO(ID_DESTINO),
	ID_FACTOR SMALLINT REFERENCES Factor.FACTOR(ID_FACTOR),
	ID_VUELTAS SMALLINT REFERENCES Vueltas.VUELTAS(ID_VUELTAS),
	ID_RAJO TINYINT REFERENCES Rajo.RAJO(ID_RAJO)
);

CREATE TABLE Material.MAT_CICL(
	ID_MAT_CICLO SMALLINT IDENTITY(1,1) PRIMARY KEY,
	ID_CICLO INT REFERENCES Ciclo.CICLO(ID_CICLO),
	ID_MATERIAL SMALLINT REFERENCES Material.MATERIAL(ID_MATERIAL)
);

CREATE TABLE Registro.REGISTRO(
	ID_REGISTRO SMALLINT IDENTITY(1,1) PRIMARY KEY,
	ID_FACTOR_CARGA SMALLINT REFERENCES Factor.FACTOR_CARGA(ID_FACTOR_CARGA),
	ID_CICLO INT REFERENCES Ciclo.CICLO(ID_CICLO),
	ID_FACTOR_ANTERIOR SMALLINT REFERENCES Factor.FACTOR(ID_FACTOR)
);

CREATE TABLE [User].ADMINISTRADOR(
	ID_ADMIN TINYINT IDENTITY(1,1) PRIMARY KEY,
	ID_RAJO TINYINT REFERENCES Rajo.RAJO(ID_RAJO),
	CORREO VARCHAR(255) NOT NULL UNIQUE,
	CONTRASENIA VARCHAR(MAX)
);

CREATE TABLE [User].USUARIO(
	ID_USUARIO TINYINT IDENTITY(1,1) PRIMARY KEY,
	ID_RAJO TINYINT REFERENCES Rajo.RAJO(ID_RAJO),
	CORREO VARCHAR(255) NOT NULL UNIQUE,
	CONTRASENIA VARCHAR(MAX)
);

CREATE VIEW Ciclo_Vista AS 
SELECT FE.FECHA AS Fecha,PA.NOMBRE AS Carguio, CAM.NOMBRE AS Camión, FLO.NOMBRE AS Flota, 
	   MAT.NOMBRE AS Material, ORI.NOMBRE AS Origen, ZO.NOMBRE AS Zona, DEST.NOMBRE AS Destino,
	   VUE.CANTIDAD*FAC.TONELAJE AS Tonelaje, VUE.CANTIDAD AS Ciclos, RAJ.NOMBRE AS Rajo
FROM Ciclo.CICLO AS CI
INNER JOIN Fecha.FECHA AS FE
ON CI.ID_FECHA=FE.ID_FECHA
INNER JOIN Pala.PALA AS PA
ON CI.ID_PALA=PA.ID_PALA
INNER JOIN Camion.CAMION AS CAM
ON CI.ID_CAMION=CAM.ID_CAMION
INNER JOIN Camion.FLOTA FLO
ON CAM.ID_FLOTA=FLO.ID_FLOTA
INNER JOIN Material.MAT_CICL AS MC
ON CI.ID_CICLO=MC.ID_CICLO
INNER JOIN Sector.ZONA AS ZO 
ON CI.ID_ZONA=ZO.ID_ZONA
INNER JOIN Sector.ORIGEN ORI
ON ZO.ID_ZONA=ORI.ID_ZONA
INNER JOIN Sector.DESTINO AS DEST
ON CI.ID_DESTINO=DEST.ID_DESTINO
INNER JOIN Vueltas.VUELTAS VUE
ON CI.ID_VUELTAS=VUE.ID_VUELTAS
INNER JOIN Rajo.RAJO RAJ
ON CI.ID_RAJO=RAJ.ID_RAJO
INNER JOIN Material.MATERIAL AS MAT
ON MAT.ID_MATERIAL=MC.ID_MATERIAL
INNER JOIN Factor.FACTOR FAC
ON CI.ID_FACTOR=FAC.ID_FACTOR